### ISSUE TITLE
Remove blank lines defconfig2 between non-msix and msix builds

### ISSUE THREAD

**Issue by JonathanPitre** [ItzLevvie/MicrosoftTeams-msinternal#5]
Would it be possible to remove the blanks lines between the non-msix and msix builds ? I wrote a regex to capture the version and urls and with that blank line in between it makes it darn impossible.

https://raw.githubusercontent.com/ItzLevvie/MicrosoftTeams-msinternal/master/defconfig2

![image](https://user-images.githubusercontent.com/15003329/143982431-8923aec1-85fc-4fd8-823c-bb84920885ba.png)

Thank you

**Comment by ItzLevvie** [comment]
Fixed in https://github.com/ItzLevvie/MicrosoftTeams-msinternal/commit/8c88cf4c641b393c2f113088989aff75c260185e.

**Comment by ItzLevvie** [comment]
Oops, I just realized that you should probably keep using the "E (Electron only)" builds because it's usually ahead of the Canary (Ring 0) deployment.

Internal WebView2 builds are only useful for internal folks. If you're not a Microsoft employee, vendor/contractor, or partner, installing MSIX builds will downgrade you to the latest public release.

**Comment by JonathanPitre** [comment]
Thanks much appreciated!

I'll stick to the public preview and public builds for WebView 2 then.
